### ISSUE TITLE
تکمیل صفحه پروفایل

### ISSUE THREAD

**Issue by kerasus** [alaatv-front/alaatv-front#132]
https://github.com/kerasus/alaatv-front/issues/45

**Comment by ali-khoshnevisan** [comment]
![image](https://user-images.githubusercontent.com/102961740/199032323-48e49773-eb51-46d8-b332-618c59872cb1.png)
در صفحه ی پروفایل، api ثبت رتبه نداریم.
eventresult

**Comment by ali-khoshnevisan** [comment]
در صفحه ی پروفایل، api ثبت رتبه نداریم.
eventresult

![image](https://user-images.githubusercontent.com/102961740/199032504-bff81ff9-76f8-4344-b569-37cfec5649b4.png)
