### ISSUE TITLE
تکمیل صفحه نقشه راه ابریشم

### ISSUE THREAD

**Issue by kerasus** [alaatv-front/alaatv-front#146]
در آدرس 
/map
می بایست نقشه راه ابریشم تمام صفحه باز شود
و پنل ادمین نقشه راه ابریشم بررسی شود

**Comment by mitraKhm** [comment]
به علت انجام تسک لندینگ پنالتی ایت تسک به اتمام نرسید.

**Comment by ali-khoshnevisan** [comment]
ای برای حذف و ویرایش مارکر وجود ندارد  Api ثبت مارکر و دریافت نود ها ارور ۵۰۳ میدهد. همچنین هیچ  Api
