### ISSUE TITLE
ساخت سبد خرید

### ISSUE THREAD

**Issue by kerasus** [alaatv-front/alaatv-front#32]
صفحه سبد خرید طبق فیگما لینک زیر انجام شود.
https://www.figma.com/file/I8ZNj7ptM4MWjqT4aHj7Zp/Alaa-Cart
ریکوست بررسی اطلاعات سبد خرید در ایشو #31 ایجاد شده.
با استفاده از آن اطلاعات صفحه را بسازید.

**Comment by mitraKhm** [comment]
- اصلاح چیدمان کلی صفحه
- اصلاح برخی از استایلهای کامپوننت های مجاور
- اضافه کردن کد تخفیف
- به علت نداشتن ای پی ای فرایند ثبت و حذف کد تخفیف انجام نشده است بنابراین تسک ب اتمام نرسید
