### ISSUE TITLE
فورک و نصب پروژه روی سیستم جدید

### ISSUE THREAD

**Issue by Archer-Thane** [alaatv-front/alaatv-front#54]
برای فورک و نصب پروژه روی سیستم های جدید، اول از همه باید وابستگی های پروژه را با آخرین ورژن نود (۱۸.۷) نصب شوند. در این صورت خطا روی scss خواهیم داشت. 
سپس باید ورژن نود به (۱۶.۱۶) تغییر یابد تا پروژه به درستی راه بیافتد. 
استفاده از nvm توصیه می شود. 
این را بیشتر برای یادآوری برای فعال کردن سیستم های جدید در آینده می نویسم؛ ولی اگر بتوانیم این مشکل را حل کنیم بسیار عالی است (یا آخرین ورژن در دسترس باشد و نصب و راه اندازی توسط آن انجام شود و یا ورژن ۱۶.‍۱۶ نصب و راه اندازی روی آن باشد)

**Comment by Saeed-Paris** [comment]
@Archer-Thane سلام من اشنایی زیادی با بک اند ندارم.میخاستم بدونم برای دسترسی به صفحه های مربوط به یوزر در فرانت باید لاگین کنیم؟

**Comment by Archer-Thane** [comment]
سلام بعضی از صفحه ها نیاز به لاگین بودن دارن و باید لاگین کنید. اگه لاگین کنید یه توکن دسترسی بهتون می ده که با استفاده از اون می تونید به بک اند دسترسی پیدا کنید. 
کلا نظم بک اند بر این بنا ست که 
۱- یا کاربر لاگین نکرده و نیازی هم به لاگین نیست (داده ی عمومیه)
۲- کاربر لاگین کرده و یه نقش مشخصی هم داره و می تونه به یه اطلاعات مشخصی دسترسی داشته باشه. (اگه لاگین نباشه و درخواست بده کد http عدد ۴۰۱ می شه)
۳- کاربر لاگین کرده ولی نقش لازم برای دسترسی رو نداره. در این صورت خطای دسترسی غیر مجاز می ده.(اگه نقش نداشته باشه کد ۴۰۳ می گیره)

**Comment by Saeed-Paris** [comment]
سلام من تازه پروژه رو نصب کردم میخواستم ببینم برای این که بخوام تو لوکال خودم به روتی دسترسی داشته باشو باید از فایل routes.js پیدا کنم یا نه؟ چون هدر با هدر تو فیگما فرق داره! @Archer-Thane
