### ISSUE TITLE
مشکلات api

### ISSUE THREAD

**Issue by kerasus** [alaatv-front/alaatv-front#95]

**Comment by Archer-Thane** [comment]
در صفحه ی پروفایل بخش زیر باید اضافه گردد:
**eventresult**
![Screenshot from 2022-08-16 13-04-18](https://user-images.githubusercontent.com/17456531/184835344-f8851df3-39e4-4b47-9f2c-7e38a924dc6a.png)

**Comment by Archer-Thane** [comment]
در صفحه ی پروفایل، آپلود عکس به درستی انجام نمی شود. فایل باینری به آدرس زیر ارسال می شود:
Request URL: http://localhost:8083/alaa/api/v2/user/$userId
متد PUT
![Screenshot from 2022-08-16 15-05-08](https://user-images.githubusercontent.com/17456531/184859501-90c787e6-135c-498b-8be3-1dd5fc90ff4e.png)
![Screenshot from 2022-08-16 15-05-14](https://user-images.githubusercontent.com/17456531/184859511-7e82c8bb-ddd7-4b36-861d-cbbf2ac93335.png)

**Comment by JasGH** [comment]
در ای پی آی /checkout/review کلید grand باید اطلاعات کامل یک محصول را داشته باشد :

![image](https://user-images.githubusercontent.com/81778219/186635699-5bbffde2-6f14-4ae0-a8db-170e3ecba305.png)
--------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/81778219/186635739-637a4a7a-1f3a-42f1-9fa4-1dde9d8eba73.png)

**Comment by Ayhanemoon** [comment]
api مشكل حذف محصول از سبد خريد #96
اين api، ارور 403 ميده. بعضي وقتا هم 404!
alaa/api/v2/orderproduct/productId

**Comment by Ayhanemoon** [comment]
API for get departments

by lookzadeh

**Comment by JasGH** [comment]
در روت 
/api/v2/product/...
در مقایسه با روت 
/ajax/product/757
برخی از کلید های موجود از جمله has_instalment_option (و یا is_favored_2) وجود ندارد . 


-------------------------------------------------------------------------------------------------------

ای پی آی برای بنر تبلیغاتی وجود ندارد .

-----------------------------------------------------------------------------------------------------------
کلید is_favored در روت های :
/api/v2/set/...

/api/v2/c/.....
و
/api/v2/product/...

وجود ندارد

**Comment by JasGH** [comment]
نیاز داریم با ریکوعست زدن به یک اندپوینت تگ اسکریپت چی بخونم را نشان بدهیم . در حال حاضر برای این مورد اقدامی صورت نگرفته است.

**Comment by JasGH** [comment]
ریسپانس کلید related_product در روت 
/api/v2/c/.....
 با دیتایی که در بلید به صورت مستقیم از دیتابیس خوانده میشود متفاوت است.

**Comment by JasGH** [comment]
گرفتن VAST از ای پی آی

**Comment by mitraKhm** [comment]
ایجاد api برای دریافت دسته های محصولات 
![image](https://user-images.githubusercontent.com/72399981/197694559-bce2ded8-c5a7-4978-9afe-0a07975bfd8c.png)

و همچنین ایجاد api برای دریافت کل محصولات ( product ) کاربر به همراه ایدی set ها .نمونه اطلاعات مورد نیاز : 
![image](https://user-images.githubusercontent.com/72399981/197696244-0ecc60ab-4a22-4ba6-bded-c978600b575e.png)


و همچنین ایجاد api برای دریافت علاقه مندی های کاربر یعنی هر انچه کاربر تا به حال بوک مارک کرده است که شامل محصولات و مجموعه ها ویا فیلم ها میشود 
این دیتاها برای صفحه ی فیلم ها و جزوه های من نیاز است و عملا بدون داشتن این api ها پیاده سازی این صحفه در پروژه ی alaa vue امکان پذیر نمیباشد. 
این دیتا ها در حال حاضر در بلید    
dashboard.blade.php
موجود میباشد. (جهت برسی ساختار داده)

**Comment by mitraKhm** [comment]
ایجاد روت های مربوط به کد تخفیف ( ثبت  حذف ... ) در مسیر 
/api/v2/....

**Comment by mitraKhm** [comment]
ایجاد ای پی ای جهت دریافت وضعیت پرداخت در مسیر 

/api/v2/payment/status
همچنین ای پی ای برای دریافت سفارشات کاربر 
api/v2/orders

**Comment by mitraKhm** [comment]
ایجاد ای پی ای جهت دریافت دپارتمانهای تیکت 
![image](https://user-images.githubusercontent.com/72399981/204129263-b31feacc-6f0a-41c9-a6ce-896b3d3dff18.png)

**Comment by mitraKhm** [comment]
در api ارسال تیکت قابلیتی داریم تحت عنوان ارسال فایل. وقتی فایلی ارسال میشود (بدون متن و عکس و صدا ) این رسپانس را دریافت میکنیم : 
![image](https://user-images.githubusercontent.com/72399981/204139171-55687297-1418-410b-8760-577f12d602f0.png)
422

![image](https://user-images.githubusercontent.com/72399981/204139204-a5d581a3-fdee-4b1d-98e1-fc20d6d4a268.png)

باید قابلیت ارسال فایل بدون متن یا صدا یا عکس را داشته باشیم .

**Comment by mitraKhm** [comment]
ایجاد دو ای پی ای جهت دریافت مسئول و  پاسخگو تیکت (ادمین) .
درحال حاضر این دیتا از بلید  
ticket.blade.php
تحت عنوان user-supporters و user-assignees
به فرانت اند ارسال میشود.

**Comment by ali-khoshnevisan** [comment]
ای پی آي دریافت محصول کلیدی برای پیاده سازی محتوای ((هدایا)) ی محصولات نمیدهد
مثال:‌ محصول 793

**Comment by ali-khoshnevisan** [comment]
ای پی آی دریافت محصول نمونه فیلم ها را در response نمیفرستد
مثال: محصول 421
![Screenshot from 2022-12-25 15-01-02](https://user-images.githubusercontent.com/102961740/209466995-60bc0312-8803-4399-a0bf-2836b56bbcd3.png)

**Comment by ali-khoshnevisan** [comment]
عدم وجود ای پی آی محصولات مرتبط برای کانتنت ها

**Comment by ali-khoshnevisan** [comment]
عدم وجود پرمیشن در ای پی آی محصول برای امکان یا عدم امکان دسترسی به فیلم ها و جزوات قبل از خرید محصول
مثال: محصول 421

**Comment by ali-khoshnevisan** [comment]
در ای پی آی دریافت کانتنت نمونه فیلم یک محصول باید یک کلید وجود داشته باشد که مشخص کند آیا کاربر محصولات مربوط به این کانتنت را خریده یا نه.
تصویر کانتنت 33045 است که مربوط به دو محصول تتای حفظیات شیمی و تتای حل مسایل شیمی کنکور است

![Screenshot from 2022-12-25 15-49-18](https://user-images.githubusercontent.com/102961740/209468111-21c349a7-e0e3-44e4-b187-6643967d0b78.png)

**Comment by ali-khoshnevisan** [comment]
ای پی آی دریافت محصول محتویات فیلم ها و جزوات محصول را نمیفرستد

![Screenshot from 2022-12-25 15-03-39](https://user-images.githubusercontent.com/102961740/209468704-366a233d-5c09-4b2f-9d34-5c056cdc483a.png)

![Screenshot from 2022-12-25 15-03-49](https://user-images.githubusercontent.com/102961740/209468709-67f564d1-7985-4727-b577-7a32ff238fe9.png)

**Comment by mitraKhm** [comment]
در داشبورد ابریشم قسمت اخبار و اطلاعیه به آدرس : 
/asset/abrisham#/news
از بلید   
dashboardAbrisham.blade.php
به ادرس : 
resources/views/user/dashboardAbrisham.blade.php
داده هایی از php دریافت میشود که لازم است برای آن api تعریف شود. 
newsPageBannersو abrishamProductsوAPIAddressesوcontentSearchوApibaseUrl
